#ifndef _PL_CONFIG_HH_INCLUDED_
#define _PL_CONFIG_HH_INCLUDED_

#define PL_WALK_CAMERA_PERSPECTIVE_FOV 45.0f
#define PL_WALK_CAMERA_PERSPECTIVE_NEAR 0.01f
#define PL_WALK_CAMERA_PERSPECTIVE_FAR 1000.0f

#define PL_WALK_CAMERA_SPEED 0.5f
#define PL_WALK_CAMERA_SENSITIVITY 0.05f

#endif
